pipeline {

    agent {
        label "docker-agent"
    }
    stages{
        stage("Checkout Code") {
            steps {
               git branch: 'main',url: "https://github.com/patelmanjeet/devops_assignment_collection.git"
            }
        }
        stage("Build Docker Image") {
            steps {
                dir('01-assignment/solution/task1/') {
                    sh 'docker build . -t worldclock-app:${BUILD_NUMBER}'
                    sh 'docker tag worldclock-app:${BUILD_NUMBER} worldclock-app:latest'
                }
            }
        }
    }
}